export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN'
export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEMS'
export const CLEAR_CART = 'CLEAR_CART'

export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP'
export const REQUEST_SIGN_UP_SUCCESS = 'REQUEST_SIGN_UP_SUCCESS'
export const REQUEST_SIGN_UP_FAILURE = 'REQUEST_SIGN_UP_FAILURE'

// GOOGLE SIGN-IN
export const REQUEST_GOOGLE_SIGN_IN = 'REQUEST_GOOGLE_SIGN_IN'
export const REQUEST_EMAIL_SIGN_IN = 'REQUEST_EMAIL_SIGN_IN'

export const REQUEST_SIGN_IN_SUCCESS = 'REQUEST_SIGN_IN_SUCCESS'
export const REQUEST_SIGN_IN_FAILURE = 'REQUEST_SIGN_IN_FAILURE'

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT'
export const REQUEST_SIGN_OUT_SUCCESS = 'REQUEST_SIGN_OUT_SUCCESS'
export const REQUEST_SIGN_OUT_FAILURE = 'REQUEST_SIGN_OUT_FAILURE'

export const CHECK_USER_SESSION = 'CHECK_USER_SESSION'
// COLLECTIONS
export const REQUEST_COLLECTIONS = 'REQUEST_COLLECTIONS'
export const REQUEST_COLLECTIONS_SUCCESS = 'REQUEST_COLLECTIONS_SUCCESS'
export const REQUEST_COLLECTIONS_FAILURE = 'REQUEST_COLLECTIONS_FAILURE'

export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS'
